#!/bin/bash
D=$(dirname $0)

rm .config
make defconfig

FRAGMENTS=()
if [[ $1 =~ ^arm.* ]]; then
  FRAGMENTS+=("arm")
fi
  
FRAGMENTS+=("$*")
FRAGMENTS+=("base")
echo ${FRAGMENTS[@]}
for frag in ${FRAGMENTS[@]}; do
  if [ -e $D/$frag.config ]; then
    cat $D/$frag.config >> .config
  else
    echo "WARNING: $D/$frag.config doesn't exist.  Giving up."
    exit 1
  fi
done

# reconfigure with new fragments appended
yes "" | make oldconfig

make

# remove uncompressed versions of rootfs 
(cd output/images; rm -f rootfs.cpio rootfs.tar)

if [ $? = 0 ]; then
    echo "Packaging up output/host directory"
    tar -C output/host -Jcf output/images/host.tar.xz .
    (cd output/images; md5sum host.tar.xz > host.tar.xz.md5)
fi
